### ISSUE TITLE
crunchbase-csv.py returns error

### ISSUE THREAD

**Issue by bonysimon007** [notpeter/crunchbase-data#5]
The program returns error and says IOError: [Errno 2] No such file or directory: 'crunchbase_export.xlsx'

**Comment by notpeter** [comment]
Yeah, that script is designed to process the `crunchbase_export.xlsx` which was previously distributed under the terms of the creative commons CC-SA-NC license for educational users.

They have since shuttered this program and the repo contains CSV transformations of the data from the last known release (December 2015) under that more permissive license.  There will be no more updates to this data. Sorry.
